// File automatically generated from OpenAPI spec.
module openai.model.ChatCompletionStreamResponseDelta;

import vibe.data.serialization : vibeName = name, vibeOptional = optional, vibeEmbedNullable = embedNullable;
import vibe.data.json : Json;
import builder : AddBuilder;

import std.typecons : Nullable;


/**
 */
class ChatCompletionStreamResponseDelta {
  static class FunctionCall {
    /**
     * The arguments to call the function with, as generated by the model in JSON format. Note that
     * the model does not always generate valid JSON, and may hallucinate parameters not defined by
     * your function schema. Validate the arguments in your code before calling your function.
     */
    @vibeName("arguments")
    @vibeOptional
    @vibeEmbedNullable
    Nullable!(string) arguments;

    /**
     * The name of the function to call.
     */
    @vibeName("name")
    @vibeOptional
    @vibeEmbedNullable
    Nullable!(string) name;

    mixin AddBuilder!(typeof(this));

  }

  /**
   * The name and arguments of a function that should be called, as generated by the model.
   */
  @vibeName("function_call")
  @vibeOptional
  @vibeEmbedNullable
  Nullable!(FunctionCall) functionCall;

  /**
   * The contents of the chunk message.
   */
  @vibeName("content")
  @vibeOptional
  @vibeEmbedNullable
  Nullable!(string) content;

  /**
   * The role of the author of this message.
   */
  @vibeName("role")
  @vibeOptional
  @vibeEmbedNullable
  Nullable!(string) role;

  mixin AddBuilder!(typeof(this));

}
